CREATE DATABASE IF NOT EXISTS sms;
USE sms;
CREATE TABLE IF NOT EXISTS students (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    age INT NOT NULL,
    course VARCHAR(100),
    email VARCHAR(150) UNIQUE
);
